### ISSUE TITLE
Formatting bar and fields.select no longer working

### ISSUE THREAD

**Issue by MLorneSmith** [Thinkmill/keystatic#1304] opened 2024-09-11 19:22 UTC
Encountering an issue with the select field since the last update. The select input renders, but the array of options does not appear when clicked on.

For me the issue extends to the entire formatting bar in the editor. Nothing works. Without this, keystatic is completely broken for me.

Several comments in Discord.

[https://cdn.discordapp.com/attachments/1139018073442103397/1282731794696896535/google_screen_recording_2024-09-09T15-58_02.157Z.webm?ex=66e30f93&is=66e1be13&hm=31846fdc67ddeecd0bdb3a9d3c53938bb8c87b634d215d439b1f73a2f5cafa5a&](url)

**Comment by emmatown** [comment] 2024-09-11 23:18
I'm not able to reproduce this, can you provide a GitHub repo with a project where this happens and details on what browser you're using?

**Comment by zanhk** [comment] 2024-09-14 10:21
To me even all the button on the navbar stopped working, @emmatown  you did not reproduce because you are on mac and on mac works, it stopped working on chrome for windows.

I see these warnings in the console


![image](https://github.com/user-attachments/assets/1888a790-fee5-4de6-b25b-d1e20d10650b)

**Comment by emmatown** [comment] 2024-09-16 00:12
I've just tried to reproduce this with Chrome (128.0.6613.138) on Windows with projects created with `pnpm create @keystatic@latest`  with Astro and Next with select fields added and still haven't been able to reproduce this

**Comment by zanhk** [comment] 2024-09-23 07:36
I will test with a minimal repo to reproduce this problem

**Comment by zanhk** [comment] 2024-09-24 20:44
@emmatown I just tested and it seem to be started working again in the latest version, 


@MLorneSmith try upgrade and see if fix for you as well

**Comment by zanhk** [comment] 2024-09-24 20:52
Actually I upgraded all packages and couldn't repro anymore, tried downgrade just keystatic but it kept working, so i don't know which one of the packages was causing the problem, maybe when i will have time i will try to test, meanwhile @MLorneSmith try upgrade all packages and see if it fixes

**Comment by emmatown** [comment] 2024-12-09 05:46
Without a reproduction, I'm going to close this

**Closed by emmatown** 2024-12-09 05:46 UTC
