### ISSUE TITLE
Field validation failed: content: Unexpected error: Error: 0:paragraph has unexpected children

### ISSUE THREAD

**Issue by zanhk** [Thinkmill/keystatic#997] opened 2024-03-10 20:45 UTC
Getting the error

"Field validation failed: content: Unexpected error: Error: 0:paragraph has unexpected children"

when trying to use a multiline field in a custom component (markdoc)

[google_screen_recording_2024-03-10T20-42_44.013Z.webm](https://github.com/Thinkmill/keystatic/assets/17980844/346c27ee-1c33-4e2d-882b-6bdcbe6af2a7)

```js
ContactWithForm: block({
	label: "Form di contatto",
	icon: ContactIcon({ ariaHidden: true }),
	description: "Personalizza le informazioni relative alla form di contatto",
	schema: {
		title: fields.text({
			label: "Titolo",
			validation: {
				isRequired: true,
			},
		}),
		subtitle: fields.text({
			label: "Sottotitolo",
			validation: {
				isRequired: true,
			},
		}),
		email: fields.text({
			label: "Email",
			validation: {
				isRequired: true,
			},
		}),
		phone: fields.text({
			label: "Telefono",
			validation: {
				isRequired: true,
			},
		}),
		timetables: fields.text({
			label: "Orari",
			multiline: true, // <- here causing the problem
		}),
	},
}),

```

I would expect something like `"test\ntest"`

Thanks

**Comment by emmatown** [comment] 2024-03-12 01:36
This is caused by a bug in Markdoc, a fix has been merged but not yet released: https://github.com/markdoc/markdoc/pull/470

**Closed by emmatown** 2024-03-12 01:36 UTC

**Comment by emmatown** [comment] 2024-03-13 22:43
Nice! missed that, will get Keystatic updated
